# 세틀뱅크 IP  test:61.109.249.165  real:61.109.249.167
# server_ip=61.109.249.165
server_ip=61.109.249.167

# 세틀뱅크 포트(암호화된 전문을 받는 세틀뱅크포트)
server_port_va=30406
server_port_fm=30406

# 중계서버 포트(암호화할 전문을 수신받는 포트)
client_port=13000

# 암호화 여부, 비암호화 :0 / 암호화 : 1
enc = 1

# 암호화 KEY
key = 1234567890123456


#로그파일 관련 정보
logInfoFile=/home/crowdfund/public_html/sett/conf/log4j.properties
