<?

//일반 투자후기
$LIST = array(
			 array('isBest'=>'N', 'url'=>'https://blog.naver.com/bluesky19735/221162796916', 'title'=>'여러 업체가 공동진행한 상품에 투자',             'writer'=>'박**(an****)', 'image'=>'/images/review/img48.jpg', 'content'=>'이번에는 슈퍼푸드 원물 구매자금. 예전에 시소펀딩에서 슈퍼푸드 원물 구매를 했던거라 눈길이 가는 투자라 생각되었으며, 특히 이번에는 여러펀딩사들이 함께하는 거라서 더욱 믿음이 간 것 같다.')
			,array('isBest'=>'N', 'url'=>'https://blog.naver.com/bohwang/221169690458', 'title'=>'수익률 좋고 안정적인 헬로펀딩',             'writer'=>'황**(bo*****)', 'image'=>'/images/review/img49.jpg', 'content'=>'최근에 P2P투자를 시작하게 되었습니다. 은행에 저축을 하는 것도 이자율이 너무 낮고 주식을 잘 아는 것도 아니어서ㅠㅠ 헬로펀딩이라는 P2P업체에 투자를 하였어요')
      ,array('isBest'=>'N', 'url'=>'https://blog.naver.com/loam30/221171907318', 'title'=>'이제는 꼼꼼히 따져보고 투자합니다',             'writer'=>'정**(lo****)', 'image'=>'/images/review/img50.jpg', 'content'=>'안녕하세요. loam입니다. 요즘 제가 p2p 연체도 많고 부실채권도 많아지는 것 같아서 당분간 p2p 투자는 자제하려고 했는데 문자 보고 좋은 상품이라는 생각이 들어서 또 투자를 해버렸네요. ㅋㅋㅋ')
			,array('isBest'=>'N', 'url'=>'https://blog.naver.com/PostView.nhn?blogId=chesney0126&logNo=221133752237&navType=tl&proxyReferer=http%3A%2F%2Fm.blog.naver.com%2FPostList.nhn%3FblogId%3Dchesney0126%26currentPage%3D1', 'title'=>'헬로펀딩 네임 벨류를 믿고 투자!',             'writer'=>'김**(ch*****)', 'image'=>'/images/review/img45.jpg', 'content'=>'헬로펀딩 50호 동산담보 포트폴리오 11호에 소액 투자 하였습니다 동산담보 채권인데 2억원 11%인데 짧은 투자 기간과 헬로펀딩의 네임 벨류를 믿고 투자했네요')
			,array('isBest'=>'N', 'url'=>'http://blog.naver.com/skacks0330/221135489455', 'title'=>'헬로펀딩 동산상품의 우수성 3가지',             'writer'=>'허**(hn*****)', 'image'=>'/images/review/img46.jpg', 'content'=>'어제 헬로펀딩 동산담보 포트폴리오 11호 상품이 올라와서 투자를 완료했어요. 명품에 대해 아는게 없어서 투자 할까 말까 고민 많이 했는데 상품 설명글을 읽고 투자 결정!') 
			,array('isBest'=>'N', 'url'=>'http://blog.naver.com/qqqq820114/221147671525', 'title'=>'자금유용이 원활한 동산상품 투자!',             'writer'=>'강**(qq*****)', 'image'=>'/images/review/img47.jpg', 'content'=>'안녕하세요 이번에 투자한 상품은 헬로펀딩 [제51호] 동산담보 포트폴리오 12호 상품입니다. 헬로펀딩은 부동산 pf상품뿐만아니라 이렇게 동산담보 상품도 취급하고 있는데요')
			,array('isBest'=>'N', 'url'=>'http://blog.naver.com/explorer0802/221108181083', 'title'=>'투자가 빨리 마감되는 이유가 있네요',             'writer'=>'이**(dl*********)', 'image'=>'/images/review/img42.jpg', 'content'=>'헬로펀딩에 첫 투자했어요~~ ㅎㅎ<br>헬로펀딩은 7인으로 구성된 투자심의위원회를 만장일치로 통과해야 펀딩이 된다고 하죠? 빠르게 마감되는 이유가 다 있네요!')
			,array('isBest'=>'N', 'url'=>'http://blog.naver.com/yjykjl/221111140464', 'title'=>'P2P안전성의 바로메타! 헬로펀딩',             'writer'=>'유**(yj*****)', 'image'=>'/images/review/img43.jpg', 'content'=>'오늘은 헬로펀딩에 가입후 3번째 투자인 44호 동산담보 포트폴리오9호 후기를 포스팅해보겠습니다. 먼저 이상품은 1개월의 11%수익률 그리고 2억원 모집 상품입니다.')
			,array('isBest'=>'N', 'url'=>'https://blog.naver.com/investmentcounsellor/221129208973', 'title'=>'P2P업체의 옥석을 가려서 투자하자! ',             'writer'=>'지**(yo******)', 'image'=>'/images/review/img44.jpg', 'content'=>'P2P 업체 중에 연체와 부실 0%이고, 상품 안전장치가 많기로 유명한 헬로펀딩 투자 성공했습니다.어제 사전투자 문자 후 수분 만에 90%의 투자가 마감되어서 좌절했으나 ㅠㅠ')
			,array('isBest'=>'N', 'url'=>'https://blog.naver.com/tuing1211/221087121950', 'title'=>'내가 헬로펀딩에 투자한 이유',             'writer'=>'이***(da********)', 'image'=>'/images/review/img39.jpg', 'content'=>'오늘은 헬로펀딩의 44호 동산담보 포트폴리오 투자건에 대한 후기를 적어보고자 합니다. 포트폴리오 상품이란? 다수의 채권을 묶어 하나의 투자상품으로 설계한 것을 포트폴리오 상품이라 하며,')
			,array('isBest'=>'N', 'url'=>'http://blog.naver.com/yjykjl/221092510245', 'title'=>'42호 PF상품에 대한 정밀분석!',             'writer'=>'유**(yj*****)', 'image'=>'/images/review/img40.jpg', 'content'=>'헬로펀딩은 건설자금상품이 주로 나오고 있는데요. 관리가 많이 필요한 상품이지만 아직까지 부실과 연체없이 안전하게 상품을 상환을 시키고 있습니다. 그래서인지 재투자율이 아주 높다고 합니다.')
			,array('isBest'=>'N', 'url'=>'http://blog.naver.com/bluesky19735/221096813042', 'title'=>'헬로펀딩을 만나 내 마음도 헬로',             'writer'=>'박**(an****)', 'image'=>'/images/review/img41.jpg', 'content'=>'이번에는 1개월 단기라서 100백만원을 투척했음. 헬로펀딩이 좋은 것 아마도 심의 위원들이 만장일치로 투자심사가 결정된다는 사실이 가장 마음이 든다. ')
			,array('isBest'=>'Y', 'url'=>'https://blog.naver.com/hm8033/221066079825', 'title'=>'헬로펀딩은 확 다르네요',             'writer'=>'김**(hm****)', 'image'=>'/images/review/img31.jpg', 'content'=>'p2p 투자를 시작한 뒤로 가입 이벤트 없이 회원가입을 하는 일은 거의 없었던 것 같아요. 그런데 오늘 헬로펀딩~!!')
		  ,array('isBest'=>'N', 'url'=>'http://blog.naver.com/yjykjl/221077790785', 'title'=>'자신만의 투자전략을 세워 투자하자!',             'writer'=>'유**(yj*****)', 'image'=>'/images/review/img32.jpg', 'content'=>'헬로 펀딩 투자 후기 포스팅해보겠습니다. 병아리 투자자다보니 소액으로 시작했습니다. 10만원 투자하시면 10개월동안 매달1100원정도의...')
		  ,array('isBest'=>'N', 'url'=>'https://blog.naver.com/tuing1211/221066104073', 'title'=>'P2P투자는 나의 운명!?',             'writer'=>'이***(da********)', 'image'=>'/images/review/img33.jpg', 'content'=>'저는 사회생활 10년차 30대 여성입니다. 그동안 제 인생에는 여러가지 일이 있었음에도 저는 딱히 목돈만들기에는 관심이 없었던 것 같습니다.')
			,array('isBest'=>'N', 'url'=>'https://blog.naver.com/facemake/221083360387', 'title'=>'헬로펀딩 40호 투자후기 울산 우정동 ',             'writer'=>'이**(fa******)', 'image'=>'/images/review/img34.jpg', 'content'=>'이번 달에 투자한 울산 우정동 근린생활시설 준공자금 1차 투자후기를 남깁니다. 그전에 잠시!! 헬로펀딩에서 이번에 대단한 시스템을 마련했습니다. 바로!! 헬로 LIVE TV !!!')
		  ,array('isBest'=>'N', 'url'=>'http://blog.naver.com/bluesky19735/221069442646', 'title'=>'제41호 울산우정동 근린생활사업 ',             'writer'=>'박**(an****)', 'image'=>'/images/review/img35.jpg', 'content'=>'P2P투자를 한지 이제 근 8개월 남짓되어 가는 것 같다. 나름 P2P를 통해서 작은 여유자금으로 수익이 나서 다름 투자보다 P2P투자에 더 많은 관심을 가지게 되었다.')
			,array('isBest'=>'N', 'url'=>'http://blog.naver.com/immitance/221075993989', 'title'=>'헬로펀딩 투자후기',             'writer'=>'안**(im*******)', 'image'=>'/images/review/img36.jpg', 'content'=>'오늘은 헬로 펀딩 투자 투자일: 8월7일 투자상품: 헬로펀딩 41호 울산 우정동 근린생활시설 준공자금 2차 모집금액: 1차 10억, 2차 10억, 총 20억....')
		  ,array('isBest'=>'N', 'url'=>'http://blog.naver.com/kkk0127/221065891479', 'title'=>'헬로펀딩 40호 투자후기',             'writer'=>'인**(kk*****)', 'image'=>'/images/review/img37.jpg', 'content'=>'오늘도 새로운 P2P업체인 헬로펀딩이란 조금 익숙한? 업체에 첫투자 하였다. 26번째 투자 업체라고 하면 믿거나 말거나 ㅋㅋ')
			,array('isBest'=>'N', 'url'=>'http://blog.naver.com/chesney3/221065527900', 'title'=>'헬로펀딩 아주 칭찬해 투자후기 ',             'writer'=>'정**(ch******)', 'image'=>'/images/review/img38.jpg', 'content'=>'헬로펀딩 40호 울산 우정동 근린생활시설 준공자금 1차에 투자를 했습니다. 수익률 19% 투자기간 10개월 10억원 모집 사전투자 30%로 문자를...')
//			,array('isBest'=>'Y', 'url'=>'http://blog.naver.com/pfar1863/221045770137', 'title'=>'헬로 펀딩 가평수상호텔 투자 후기',             'writer'=>'박***(ID: pf******)', 'image'=>'/images/review/img24.jpg', 'content'=>'오늘은 헬로펀딩에 투자를 하였습니다. 오늘 투자한 상품은 가평수상호텔 준공을 목적으로 총 25억을 투자금을 모집하는 상품이었어요.')
//		  ,array('isBest'=>'N', 'url'=>'http://naver.me/GQFuunoo', 'title'=>'헬로펀딩에서 가평 수상레저호텔에..',             'writer'=>'권**(ID: ha******)', 'image'=>'/images/review/img25.jpg', 'content'=>'은행에 차곡차곡 예적금만 들어도 연 10% 수준의 수익을 올리던 시절이 있었다고 합니다. 저도 경험해보지 못한 과거의 일입니다.')
//			,array('isBest'=>'N', 'url'=>'http://cafe.naver.com/sangokushitaisen/29070', 'title'=>'헬로펀딩 36호 첫 투자 성공했네요!',             'writer'=>'김**(ID: fr*******)', 'image'=>'/images/review/img26.jpg', 'content'=>'헬로펀딩 첫 투자성공했습니다. 35호 사실 할려고 했는데 3분도 안되서 광속 마감했더라고요. 아차하는 순간 놓쳐서 36호는 대기타고 바로 투자...')
			,array('isBest'=>'N', 'url'=>'http://blog.naver.com/dnfl356/221050659572', 'title'=>'[헬로펀딩4] 동산담보포트폴리오',             'writer'=>'한**(ID: wo*******)', 'image'=>'/images/review/img27.jpg', 'content'=>'안녕하세요. 링블리에요~ 오늘 헬로펀딩 동산담보포트폴리오8 상품이 올라와서 투자를 완료했는데요!')
		  ,array('isBest'=>'N', 'url'=>'http://blog.naver.com/gaogaodl/221045238396', 'title'=>'헬로펀딩 투자해뜨!',             'writer'=>'정**(ID: je*******)', 'image'=>'/images/review/img28.jpg', 'content'=>'오늘ㅠㅠ 드뎌 투자 성공했어요 !! 아니 어제 35호 투자하려고 11시 땡! 하자마자 들어가서 투자후기 누르고 예치금 입금을 똭! 했는데!')
//			,array('isBest'=>'N', 'url'=>'https://blog.naver.com/PostView.nhn?blogId=chesney0126&logNo=221045443230&navType=tl&proxyReferer=http://m.blog.naver.com/PostList.nhn?blogId=chesney0126¤tPage=1', 'title'=>'헬로펀딩 투자후기 이벤트',             'writer'=>'김**(ID: ch*****)', 'image'=>'/images/review/img29.jpg', 'content'=>'헬로펀딩에 34호울산 신정동 주상복합 준공자금 2차에 이어 35호  가평군 수상레저호텔 준공자금 1차 에 투자를 했습니다')
//			,array('isBest'=>'N', 'url'=>'http://blog.naver.com/facemake/221062321433', 'title'=>'가평군 수상레저호텔 준공자금',             'writer'=>'이**(ID: fa******)', 'image'=>'/images/review/img30.jpg', 'content'=>'안녕하세요 기사도현겸입니다. 7월은 매일같이 야근인지라 포스팅하기가 어렵네요. 간단하게 후기 남깁니다.')
			,array('isBest'=>'N', 'url'=>'http://blog.naver.com/midoringgg/221039454952', 'title'=>'(P2P 투자) 헬로펀딩 첫투자후기',             'writer'=>'김**(ID: mi********)', 'image'=>'/images/review/img20.jpg', 'content'=>'요즘같은 저금리 시대에 연에 10% 이상의 수익률을 올릴수 있는 P2P투자를 해보았다. 내가 투자한 상품은 헬로펀딩에....')
			,array('isBest'=>'N', 'url'=>'http://blog.naver.com/dnfl356/221035095454', 'title'=>'[헬로펀딩3]동산담보포트폴리오',             'writer'=>'한**(ID: wo*******)', 'image'=>'/images/review/img21.jpg', 'content'=>'오늘도 역시나 헬로펀딩 동산담보포트폴리오 상품에 투자를..ㅋㅋ 하고 왔답니당! P2P투자 상품은 단기가 많긴해도 1개월 짜리를 찾기는 쉽지 않죠!')
			,array('isBest'=>'N', 'url'=>'http://blog.naver.com/mizisun80/221038158883', 'title'=>'헬로펀딩 투자후기',             'writer'=>'김**(ID: mi*****)', 'image'=>'/images/review/img22.jpg', 'content'=>'저는 재테크에 관심이 많아 사회 초년생 펀드?투자가 생소하던 시기부터 펀드, 주식 등 다양한 투자에 숟가락을 얹곤 했죠!')
			,array('isBest'=>'Y', 'url'=>'http://naver.me/5q3gx8Zc', 'title'=>'P2P투자, 헬로펀딩에서 해보자',             'writer'=>'권**(ID: ha******)', 'image'=>'/images/review/img19.jpg', 'content'=>'안녕하세요. 소나무숲입니다. 오늘은 헬로펀딩에 투자한 내용을 공유하고자 합니다. 헬로펀딩은 2016.9.27에 첫 상품을 출시한 바 있습니다.')
			,array('isBest'=>'N', 'url'=>'http://blog.naver.com/facemake/221035432513', 'title'=>'헬로펀딩 [33호] 동산담보',             'writer'=>'이**(ID: fa******)', 'image'=>'/images/review/img23.jpg', 'content'=>'안녕하세요. 기사도현겸입니다. 늘 가던 P2P관련 카페인 피자모에서 카페질을 하고 있었는데, 아래처럼 헬로펀딩 담당자에 투자후기 이벤트 글이....')
			,array('isBest'=>'N', 'url'=>'http://cafe.naver.com/sipsiilvan/11649',       'title'=>'헬로펀딩 투자후기입니다.',         'writer'=>'차** (ID: pd*****)', 'image'=>'/images/review/img07.jpg', 'content'=>'헬로펀딩 투자 후기입니다.언제나 순식간에 마감되는 헬로펀딩이네요. 오늘도 대기타다가 간신히 성공했습니다. 회원님들도 성투하세요~~')
			,array('isBest'=>'N', 'url'=>'http://blog.naver.com/shj70631/220993247989',  'title'=>'헬로펀딩 투자~이벵~~ㅎㅎ',         'writer'=>'신** (ID: sh*****)', 'image'=>'/images/review/img08.jpg', 'content'=>'헬로펀딩 이벤트!!칭찬해~~~~ 이런 이벤트가 있다니 칭찬해~!! 시험삼아? 그냥,,,,,10만원을 저저번달에???해보았다,,,')
		  ,array('isBest'=>'Y', 'url'=>'http://my799cc.blog.me/220975173703', 'title'=>'헬로펀딩 첫 투자 건 상환완료!!!', 'writer'=>'정** (ID: vi*****)', 'image'=>'/images/review/img18.jpg', 'content'=>'1월에 헬로펀딩을 따라 가출했던 제 100만원이 3개월 유랑생활을 거친 후 29,461원을 등에 업고 돌아왔습니다.')
			,array('isBest'=>'Y', 'url'=>'http://blog.naver.com/cs911420/220993522947',  'title'=>'[P2P투자]헬로펀딩 투자 이야기',    'writer'=>'이** (ID: do*****)', 'image'=>'/images/review/img04.jpg', 'content'=>'P2P투자를 접한지 벌써 7개월이라는 시간이 지나갔다. 여러 P2P업체중에 내가 믿고 투자 하는 업체... 작년 12월부터 투자하고....')
			,array('isBest'=>'Y', 'url'=>'http://blog.naver.com/ips4318/220995221289',   'title'=>'헬로펀딩 아주칭찬해! 리얼 후기!',  'writer'=>'김** (ID: op*****)', 'image'=>'/images/review/img01.jpg', 'content'=>'안녕하세요. 오늘은 제가 투자 하는 P2P업체인 헬로펀딩 (hellofunding.co.kr) 투자 후기 및 장점! 칭찬을 적어보려고 합니다~')
			,array('isBest'=>'N', 'url'=>'http://blog.naver.com/shj70631/220993247989',  'title'=>'헬로펀딩 투자후기 [제21호]',       'writer'=>'정** (ID: wj*********)', 'image'=>'/images/review/img09.jpg', 'content'=>'요즘에 많은 p2p업체가 생겼죠~그중에서 좋은 p2p 업체를 고르는 능력이 중요한데요 내돈을 얼마나 보호장치가 잘되어있는가가 중요합니다.')
			,array('isBest'=>'Y', 'url'=>'http://dilosss.tistory.com/3',               'title'=>'헬로펀딩, 24호 (주)부즈',          'writer'=>'김** (ID: di*****)', 'image'=>'/images/review/img05.jpg', 'content'=>'투자 알림을 지금은 꺼둔 상태인데, 그래도 자주(거의 매일) 펀딩 사이트들을 둘러본다. 그러다가 발견했지. 헬로펀딩에 새로운....')
			,array('isBest'=>'Y', 'url'=>'http://blog.naver.com/smilkity/220993466982',  'title'=>'헬로펀딩 독산동 메이퀸컨벤션....', 'writer'=>'이** (ID: sm******)', 'image'=>'/images/review/img03.jpg', 'content'=>'요즘 정말정말 핫한 헬로펀딩 투자후기에요~~♡ 정말 엄청난 인기에요~ 이렇게 인기 있는데는 다 이유가 있는듯요.')
			,array('isBest'=>'N', 'url'=>'http://blog.naver.com/bhm8912/220994823136',   'title'=>'크라우드펀딩 :: 헬로펀딩 투자후기', 'writer'=>'백** (ID: ba******)', 'image'=>'/images/review/img10.jpg', 'content'=>'제가 작년부터 쭈욱 재테크 하고있는 P2P 크라우드펀딩 회사를 알려드릴까 하는데요 헬로펀딩입니다 ~')
		);

//BEST 투자후기 배열번호 설정
$BEST = array('12','13', '31');


?>